# Generated by Django 3.2.7 on 2021-11-05 23:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminpanel', '0002_auto_20211105_2147'),
    ]

    operations = [
        migrations.AddField(
            model_name='cams',
            name='note',
            field=models.TextField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='devices',
            name='note',
            field=models.TextField(blank=True, max_length=200),
        ),
    ]
