# Generated by Django 3.2.7 on 2021-11-20 14:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adminpanel', '0004_alter_otp_code'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cams',
            old_name='camstatus',
            new_name='status',
        ),
    ]
