# Generated by Django 3.2.6 on 2021-12-23 07:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminpanel', '0005_rename_camstatus_cams_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cams',
            name='camname',
            field=models.CharField(default='cam', max_length=50),
        ),
        migrations.AlterField(
            model_name='devices',
            name='name',
            field=models.CharField(default='new device', max_length=50),
        ),
    ]
